spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
ftp:
  host: ${FTP_HOST}
  port: ${FTP_PORT}
  user: ${FTP_USER}
  password: ${FTP_PASSWORD}