spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:flyway
scheduler:
  dummy: 0 */1 * * * *
application:
  name: FTP over HTTP server
  description: Luxdone recruitment task
  version: 1.0.0
  creator:
    name: Marcin S
    url: https://www.szczeliniak.pl
    email: marcin@szczeliniak.pl